File name H029#4.D2


	"Swale" denotes a marshy or swampy depression of limited extent.  "Swale" is often described as wet, low, or grassy and may denote variously a low place in a field, a low, narrow strip in a meadow, swamp, a small valley, or a marsh.

