File Name:  H031#5.D2
®TS5¯
	The field workers elicited a variety of terms for different kinds of roads; the number and kinds of responses vary according to the interest and experience of field workers and informants, their knowledge of governmental rules, and the time at which the interviews were conducted.  (Should note somewhere that RIM's former experience [however phrased] or general interests caused him to seek and record a considerably greater number of terms than GSL?)
	The development of the automobile has changed the type and amount of road financing.  The first federal highway act was passed in 1916; state highways departments were established "c" 1920; the paving of secondary roads came in the 1930s (connected with the relief programs of the new deal); the Interstate Highway system (built to military specifications) was established in 1954.  As a result, the classification of roads is difficult and complicated.  The lists in this section recognize these complications.
(1)	"Road" as a pronunciation item

(2)	Major roads
	(a) By formal status, construction and maintenance by state or federal government:  							Highways, es. state û, federal û, super-, interstate (û), "main" "road", "big" û.

	(b)	Roads with a permanent surface requiring minor or occasional repairs: asphalt 										road, black top û, brick û, concrete û, tar and gravel û

(3)	Less important roads
	(a)	Roads built and maintained by county or local government: "county" "road", conces									"sion", "public" "road"; often defined by informants as highways.

	(b)	Roads subsidiary to more important roads: "back" "roads", "side" "road", "lateral" "road", 											"county""" "road", "secondary" "road", "farm" "to" "market" "road", ["pickup" road] (2) in PA], "pest" 									"road""", "school" "bus" "road"

	(c)	Roads with surfaces needing constant attention: "dirt" "road", "sand" - "clay" "road", "sand" 									and "gravel" "road", "clay" "road", "gravel" "road", "shell" "road"

(4)	Short roads, built and maintained for local conveniences at (voluntary) private 													expense, often on one family's land (private road) or shared by a group of families 							(neighborhood road); "plantation" "road" and "farm" "road" may be used in either sense.

	"private" "driveway", "lane", "avenue" ("gap")

(5)	"path", "sidewalk" and the like

**************************
**************************
Problems

	Note:  In "2b" and "3c" sometimes the field worker recorded the material ("cement", "concrete", "blacktop").  If need to differentiate is felt, suggest the instances with "road" be set down in the list as, say "concrete" "r". or "concrete" û; then after a semicolon "cement" "blacktop".  Not sure how necessary `Exotic' materials used not on roads but on city streets, or streets paved with such material, should be set down in the commentary for 2b e.g. "Belgian" "blocks" in Charleston.

	gap  `lane' but = `opening or gateway in fence' may be enough for a subsidiary list; otherwise put in commentary.

	"cow" "pass" "cattle" "pass" and the like are often marked by road signs (esp. in NY state) as prescribed places for leading cattle across a public road (probably enough for a subsidiary list).

	Note:  Types or construction and function: until fairly recently paved roads. (Limited to the vicinity of urban areas and to a few inter city roads in densely populated areas.)  With the paving of secondary roads the distinction between "highways" as paved and "side" "roads" as dirt or gravel ceased to exist.  The distinction between "paved" "road" (concrete, sheet asphalt, brick) and less durable "blacktop" or "surface" "treated" involves a knowledge of road construction that few lay informants possess; the distinction has been further obscured as older paved roads -- disintegrating with age, weather, and heavy traffic -- have been resurfaced with asphalt.  The editors feel that it is least confusion to list all types of paved roads in one list and unpaved surfaces in another.  While retaining informants' comments on historical distinctions.

