File Name:  H019#8.D2
®TS5¯
	The informants were asked what they called the amount of wood that one could carry to the stove or the fireplace on one's arm.
	The following expressions are all in use:  "turn" "of" "wood" (wide-spread); "armful" û (mostly north of the Potomac and in western NC); "armload" û (on Delaware Bay); "load" û (west of Blue Ridge); "arm" û (scattered); "burden" û (85).
