File Name: H029#7.D2
®TS5¯	"Loam" was systematically investigated in the North Central and Middle Atlantic States and in the preliminary South Atlantic survey; McDavid however, included it in SAS for SC, GA and FL.
	Lowman sought the term as a pronunciation item while McDavid asked informants to name local soil types.
	"Loam" as an adjective, either alone or in a compound, is in the commentary.  Other soil types, not containing the term "loam", are in list 35a ("muck").  "Fertile" is in list 39b.
