File name H029#4.D2


	"Swale" denotes a marshy or swampy depression of limited extent.  It was recorded mostly in New York and Northern Pennsylvania.  Lowman elicited "swale" by asking the name for a low piece of ground running through a meadow; McDavid usually sought the  name for a low, wet place smaller than a swamp.  Other terms in the list are "swale" "hole" and "swaly" "spot".  "Swale" "marsh" (NY45a) is supplied from list 37 Marsh.

