File name: H029#3.D2

	"Hollows" and "coves" are small valleys or depressions surrounded by hills or mountains.  Most of the instances of "hollow" on this list were recorded in addition to terms for "ravine" (List 41a), which was systematically investigated only in the preliminary survey of the South Atlantic States.  There are also a number of examples of "hollow" and "cove" recorded incidentally, usually in mountainous or hilly areas.  Note that there are fifteen examples of "hollow" on the main "Lowland" list.  Three place names (ONT 10; NY 57a, 62b) are included in the commentary.  See the inventory on p. 340 for the normal spelling of these names and the terms on the list.
