File Name:  H029#5.D2

	"Swamp" was given by nearly all informants as the term for land covered with water all or part of the year.  A number of other terms were offered as well; an inventory of terms is given below.  Additional examples of "swamp" will be found in List 36a (Swamp Names) where proper names of swamps recorded by the field workers are entered.  See List 34 ("Lowland"), List 35 ("Meadow"), and List 37 ("Marsh") for still other examples of "swamp", including compounds.  For additional examples of other terms, including "bog", "pond", "slash", and their compounds, see the lists containing terms for both topographical features, and for water features, especially List 36b ("Bog"), and also List 46a ("Pond"); note also the comparisons in the commentaries of the several lists.
	Some informants offered the response "marsh" in addition to "swamp".  The distinctions between the terms can be found in the commentary; additional comparisons will be found in List 37 ("marsh").
	"Swamp" is often described as overgrown with trees, thickets, or bushes.  The symbol ®MDSU¯2" designates instances of "swamp" which denote a flowing stream of water as well as the adjacent overgrown lands.  These were recorded in the coastal plain from Maryland to Florida.  Examples of "swamp" and "river" "swamp" which were recorded on page 30 of the work sheets as terms for streams are also entered in this list with the symbol ®MDSU¯2".  Examples of "branch" and "run" with a meaning analogous to "swamp®MDSU¯2" are entered in List 47 ("Branch", "Run").
	"Pocosin", recorded mainly in North Carolina, and "bay", recorded mainly in South Carolina, denote in common a swamp without an outlet. "Pocosin" is sometimes a densely overgrown swamp.  "Bay" (i.e. "Carolina" "Bay") is a shallow, elliptical depression found throughout the coastal plain, but most commonly in the Carolinas; it may have vegetation of a different character than adjoining lands.  Where "bay" refers to some part of a swamp it is entered in the commentary; examples of "bay" which refer to a body of water are entered in List 46a ("Inlet").
	Terms for a high or grassy place in a swamp are entered in the commentary; see the inventory of terms for a complete list.  McDavid recorded these terms as part of the description of swamps, whereas Lowman recorded them in seeking the names of small elevations, e.g. "hill", "knoll", in the Preliminary Survey of the South Atlantic States.
